from pptx import Presentation
from pptx.util import Pt
from datetime import datetime
import os

def create_presentation(topic, slides):
    """
    Takes generated slide data and creates a PowerPoint (.pptx) file.
    Returns the absolute path to the created file.
    Handles malformed slide data safely.
    """
    prs = Presentation()
    title_slide_layout = prs.slide_layouts[0]
    content_slide_layout = prs.slide_layouts[1]

    # Title Slide
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = topic
    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = "Generated by AI Presentation Maker"

    # Normalize slides: ensure list of dicts with "title" and "points"
    cleaned_slides = []
    for s in slides:
        if isinstance(s, dict):
            title = s.get("title", "Untitled Slide")
            points = s.get("points", [])
        elif isinstance(s, str):
            title = s[:50]  # use first 50 chars as a fallback title
            points = [s]
        else:
            title = "Untitled Slide"
            points = [str(s)]
        cleaned_slides.append({"title": title, "points": points})

    # Create content slides
    for slide_data in cleaned_slides:
        slide = prs.slides.add_slide(content_slide_layout)
        slide_title = slide.shapes.title
        slide_title.text = slide_data["title"]

        if len(slide.placeholders) > 1:
            content_box = slide.placeholders[1]
            points = slide_data["points"]

            # Normalize points (flatten lists or nested)
            if isinstance(points, str):
                points = [points]
            elif not isinstance(points, list):
                points = [str(points)]

            # Convert everything to clean text
            clean_points = [str(p).strip() for p in points if p and str(p).strip()]
            if clean_points:
                content_box.text = "\n• " + "\n• ".join(clean_points)
            else:
                content_box.text = "No content available."

            # Adjust font size
            for paragraph in content_box.text_frame.paragraphs:
                for run in paragraph.runs:
                    run.font.size = Pt(18)

    # Save presentation
    os.makedirs("outputs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_topic = "".join(c if c.isalnum() or c in ('_', '-') else "_" for c in topic)
    file_path = f"outputs/{safe_topic}_{timestamp}.pptx"
    prs.save(file_path)

    return os.path.abspath(file_path)
